site_name: Manala
repo_url: https://github.com/manala/manala/
repo_name: Manala

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: ðŸ”—

theme:
  name: material
  palette:
    primary: 'deep orange'
    accent: orange
  logo: images/manala.svg
  favicon: images/favicon-96x96.png

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Overview: overview.md
  - Usage: usage.md
  - Commands:
    - manala: commands/manala.md
    - manala init: commands/manala_init.md
    - manala list: commands/manala_list.md
    - manala update: commands/manala_update.md
    - manala watch: commands/manala_watch.md
  - Contributing: contributing.md
